- name: Install GitOps Operator
  k8s:
    state: present
    definition: "{{ lookup('template', 'subs-gitops.yml.j2') }}"

- name: Wait for GitOps CRD to exist
  k8s_info:
    api_version: "apiextensions.k8s.io/v1"
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop: "{{ gitops_expected_crds }}"
  register: crds
  until: crds.resources|length > 0
  retries: 30
  delay: 10

- name: Create rolebinding
  k8s:
    state: present
    definition: "{{ lookup('file', 'rolebinding.yaml') }}"
    wait: yes