apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canary-istio

generatorOptions:
  annotations:
    sidecar.istio.io/inject: 'true'
    
resources:
- namespace.yaml
- RolloutManager.yaml
- service-mesh-member-roll.yaml
- canary-rollout.yaml
- canary-service.yaml
- canary-route.yaml
- canary-preview-service.yaml
- canary-preview-route.yaml
- canary-virtualservice.yaml
